# Generated by Django 4.2.9 on 2024-03-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0004_rename_sсhol_class_typestudentwork_school_class'),
        ('user', '0002_sсholclass_remove_user_is_staff_user_student_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SсholClass',
            new_name='SchoolClass',
        ),
    ]
