# Generated by Django 4.2.10 on 2024-02-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_studentwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubjectGrade',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
