# Generated by Django 4.2.10 on 2024-02-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_studentwork'),
        ('user', '0006_remove_album_user_delete_subjectgrade_delete_album'),
    ]

    operations = [
    ]
