# Generated by Django 4.2.10 on 2024-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_class_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_num',
            field=models.CharField(choices=[('5А', '5А'), ('5Б', '5Б'), ('5В', '5В'), ('5Г', '5Г'), ('5Д', '5Д'), ('6А', '6А'), ('6Б', '6Б'), ('6В', '6В'), ('6Г', '6Г'), ('6Д', '6Д'), ('7А', '7А'), ('7Б', '7Б'), ('7В', '7В'), ('7Г', '7Г'), ('7Д', '7Д'), ('8А', '8А'), ('8Б', '8Б'), ('8В', '8В'), ('8Г', '8Г'), ('8Д', '8Д'), ('9А', '9А'), ('9Б', '9Б'), ('9В', '9В'), ('9Г', '9Г'), ('9Д', '9Д'), ('10А', '10А'), ('10Б', '10Б'), ('10В', '10В'), ('10Г', '10Г'), ('10Д', '10Д'), ('11А', '11А'), ('11Б', '11Б'), ('11В', '11В'), ('11Г', '11Г'), ('11Д', '11Д'), ('-', '-')], default='---', help_text='Enter class or a dash (-).', max_length=3, verbose_name='Class number'),
        ),
    ]
