# Generated by Django 4.2.10 on 2024-02-27 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
