# Generated by Django 4.2.10 on 2024-02-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_album_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_num',
        ),
    ]
