# Generated by Django 4.2.9 on 2024-02-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_class_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='users',
        ),
        migrations.DeleteModel(
            name='StudentWork',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
