# Generated by Django 4.2.9 on 2024-03-01 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.TextField(max_length=55)),
                ('image_work', models.ImageField(upload_to='example')),
                ('text_work', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=55)),
                ('writing_date', models.DateTimeField()),
                ('number_of_tasks', models.CharField(default='5', max_length=5)),
                ('image_work', models.ImageField(upload_to='image')),
                ('text_work', models.TextField(null=True)),
                ('proven_work', models.TextField(null=True)),
                ('assessment', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('example', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_work.example')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
