# Generated by Django 4.2.9 on 2024-03-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='assessment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='proven_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='text_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
