# Generated by Django 4.2.9 on 2024-02-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_work', models.ImageField(upload_to='example')),
                ('proven_work', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='image_work',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_work.example'),
        ),
    ]
