# Generated by Django 4.2.9 on 2024-02-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0002_example_alter_studentwork_image_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='proven_work',
            new_name='text_work',
        ),
    ]
