# Generated by Django 4.2.9 on 2024-03-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0003_alter_studentwork_teacher_typestudentwork_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typestudentwork',
            old_name='sсhol_class',
            new_name='school_class',
        ),
    ]
