# Generated by Django 4.2.9 on 2024-02-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0003_rename_proven_work_example_text_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='number_of_tasks',
            field=models.CharField(default='5', max_length=5),
        ),
    ]
