# Generated by Django 4.2.9 on 2024-02-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0002_alter_studentwork_image_work'),
        ('student_work', '0004_studentwork_number_of_tasks'),
    ]

    operations = [
    ]
